import { PresetColor } from './types';

export const PRESETS: PresetColor[] = [
  // == BLUE / TEAL / CYAN (25) ==
  { name: "Classic Blue", hex: "#0f62fe", cat: "Blue & Cyan" },
  { name: "Ocean Blue", hex: "#00539c", cat: "Blue & Cyan" },
  { name: "IBM Blue 60", hex: "#002d9c", cat: "Blue & Cyan" },
  { name: "Carbon Cobalt", hex: "#4589ff", cat: "Blue & Cyan" },
  { name: "Slate Blue", hex: "#2b5c8f", cat: "Blue & Cyan" },
  { name: "Deep Navy", hex: "#001d6c", cat: "Blue & Cyan" },
  { name: "Tailwind Indigo", hex: "#6366f1", cat: "Blue & Cyan" },
  { name: "Tailwind Blue", hex: "#3b82f6", cat: "Blue & Cyan" },
  { name: "Ice Blue", hex: "#1192e8", cat: "Blue & Cyan" },
  { name: "Stripe Blue", hex: "#635bff", cat: "Blue & Cyan" },
  { name: "Cyan Data", hex: "#0072c3", cat: "Blue & Cyan" },
  { name: "Pure Cyan", hex: "#00a3c4", cat: "Blue & Cyan" },
  { name: "Teal 60", hex: "#007d79", cat: "Blue & Cyan" },
  { name: "Dark Teal", hex: "#005d5d", cat: "Blue & Cyan" },
  { name: "Emerald Teal", hex: "#0d9488", cat: "Blue & Cyan" },
  { name: "Carbon Teal", hex: "#009d9a", cat: "Blue & Cyan" },
  { name: "Turquoise", hex: "#0ea5e9", cat: "Blue & Cyan" },
  { name: "Lagoon Blue", hex: "#0083b0", cat: "Blue & Cyan" },
  { name: "Cerulean", hex: "#007ba7", cat: "Blue & Cyan" },
  { name: "Prussian Blue", hex: "#003153", cat: "Blue & Cyan" },
  { name: "Steel Blue", hex: "#4682b4", cat: "Blue & Cyan" },
  { name: "Dodger Blue", hex: "#1e90ff", cat: "Blue & Cyan" },
  { name: "Cadet Blue", hex: "#5f9ea0", cat: "Blue & Cyan" },
  { name: "Midnight Teal", hex: "#042f2e", cat: "Blue & Cyan" },
  { name: "Neon Cyan", hex: "#06b6d4", cat: "Blue & Cyan" },

  // == GREEN / EMERALD / LIME (20) ==
  { name: "Forest Green", hex: "#198038", cat: "Green & Lime" },
  { name: "Carbon Green", hex: "#24a148", cat: "Green & Lime" },
  { name: "Tailwind Green", hex: "#22c55e", cat: "Green & Lime" },
  { name: "Tailwind Emerald", hex: "#10b981", cat: "Green & Lime" },
  { name: "Sage Green", hex: "#6b8e23", cat: "Green & Lime" },
  { name: "Viridis Green", hex: "#228b22", cat: "Green & Lime" },
  { name: "Leaf Green", hex: "#4caf50", cat: "Green & Lime" },
  { name: "Bright Green", hex: "#118d57", cat: "Green & Lime" },
  { name: "Moss Green", hex: "#4a5d4e", cat: "Green & Lime" },
  { name: "Dark Forest", hex: "#0e4b1f", cat: "Green & Lime" },
  { name: "Tailwind Lime", hex: "#84cc16", cat: "Green & Lime" },
  { name: "Lime Punch", hex: "#a3e635", cat: "Green & Lime" },
  { name: "Olive Drab", hex: "#6b8e23", cat: "Green & Lime" },
  { name: "Mint Leaf", hex: "#3cd070", cat: "Green & Lime" },
  { name: "Sea Green", hex: "#2e8b57", cat: "Green & Lime" },
  { name: "Kelly Green", hex: "#4cbb17", cat: "Green & Lime" },
  { name: "Jungle Green", hex: "#29ab87", cat: "Green & Lime" },
  { name: "Pine Tree", hex: "#274e13", cat: "Green & Lime" },
  { name: "Spring Green", hex: "#00ff7f", cat: "Green & Lime" },
  { name: "Jade Green", hex: "#00a86b", cat: "Green & Lime" },

  // == ORANGE / YELLOW / AMBER (18) ==
  { name: "IBM Orange 60", hex: "#ba4e00", cat: "Orange & Yellow" },
  { name: "Carbon Orange", hex: "#ff7eb6", cat: "Orange & Yellow" },
  { name: "Tailwind Orange", hex: "#f97316", cat: "Orange & Yellow" },
  { name: "Safety Orange", hex: "#ff6700", cat: "Orange & Yellow" },
  { name: "Pumpkin", hex: "#d05a3f", cat: "Orange & Yellow" },
  { name: "Amber Gold", hex: "#d97706", cat: "Orange & Yellow" },
  { name: "Tailwind Amber", hex: "#f59e0b", cat: "Orange & Yellow" },
  { name: "Warm Yellow", hex: "#eab308", cat: "Orange & Yellow" },
  { name: "Ochre Yellow", hex: "#df9f28", cat: "Orange & Yellow" },
  { name: "Tangerine", hex: "#f28e2b", cat: "Orange & Yellow" },
  { name: "Bronze", hex: "#cd7f32", cat: "Orange & Yellow" },
  { name: "Sunset Gold", hex: "#f1c40f", cat: "Orange & Yellow" },
  { name: "Marigold", hex: "#fca311", cat: "Orange & Yellow" },
  { name: "Dark Orange", hex: "#8c3b00", cat: "Orange & Yellow" },
  { name: "Sandstone", hex: "#c2a649", cat: "Orange & Yellow" },
  { name: "Mustard Gold", hex: "#e1ad01", cat: "Orange & Yellow" },
  { name: "Copper", hex: "#b87333", cat: "Orange & Yellow" },
  { name: "Clay Brown", hex: "#b35416", cat: "Orange & Yellow" },

  // == RED / PURPLE / PINK (22) ==
  { name: "Crimson Red", hex: "#da1e28", cat: "Red & Violet" },
  { name: "IBM Red 60", hex: "#a2191f", cat: "Red & Violet" },
  { name: "Tailwind Red", hex: "#ef4444", cat: "Red & Violet" },
  { name: "Scarlet", hex: "#ff2400", cat: "Red & Violet" },
  { name: "Coral Red", hex: "#e05353", cat: "Red & Violet" },
  { name: "Tailwind Rose", hex: "#f43f5e", cat: "Red & Violet" },
  { name: "Ruby Pink", hex: "#d12b6a", cat: "Red & Violet" },
  { name: "Magenta 60", hex: "#8a3ffc", cat: "Red & Violet" },
  { name: "Carbon Purple", hex: "#a56eff", cat: "Red & Violet" },
  { name: "Royal Purple", hex: "#6929c4", cat: "Red & Violet" },
  { name: "Deep Violet", hex: "#491d8b", cat: "Red & Violet" },
  { name: "Tailwind Violet", hex: "#8b5cf6", cat: "Red & Violet" },
  { name: "Tailwind Purple", hex: "#a855f7", cat: "Red & Violet" },
  { name: "Plum Purple", hex: "#800080", cat: "Red & Violet" },
  { name: "Eggplant", hex: "#31135e", cat: "Red & Violet" },
  { name: "Tailwind Fuchsia", hex: "#d946ef", cat: "Red & Violet" },
  { name: "Hot Pink", hex: "#ff69b4", cat: "Red & Violet" },
  { name: "Wine Red", hex: "#722f37", cat: "Red & Violet" },
  { name: "Burgundy", hex: "#800020", cat: "Red & Violet" },
  { name: "Mauve", hex: "#e0b0ff", cat: "Red & Violet" },
  { name: "Lavender", hex: "#b57edc", cat: "Red & Violet" },
  { name: "Amethyst", hex: "#9966cc", cat: "Red & Violet" },

  // == NEUTRALS / SLATE / COOL GRAY (15) ==
  { name: "Carbon Gray 60", hex: "#525252", cat: "Neutrals & Grays" },
  { name: "Charcoal Dark", hex: "#262626", cat: "Neutrals & Grays" },
  { name: "Tailwind Slate", hex: "#64748b", cat: "Neutrals & Grays" },
  { name: "Tailwind Zinc", hex: "#71717a", cat: "Neutrals & Grays" },
  { name: "Cool Gray Slate", hex: "#475569", cat: "Neutrals & Grays" },
  { name: "Warm Stone", hex: "#78716c", cat: "Neutrals & Grays" },
  { name: "Steel Gray", hex: "#708090", cat: "Neutrals & Grays" },
  { name: "Ash Gray", hex: "#b2beb5", cat: "Neutrals & Grays" },
  { name: "Plumbago", hex: "#3f4d63", cat: "Neutrals & Grays" },
  { name: "Gunmetal", hex: "#2a3439", cat: "Neutrals & Grays" },
  { name: "Lead Gray", hex: "#3a3a3a", cat: "Neutrals & Grays" },
  { name: "Taupe", hex: "#483c32", cat: "Neutrals & Grays" },
  { name: "Bistre", hex: "#3d2314", cat: "Neutrals & Grays" },
  { name: "Silver Gray", hex: "#8a9597", cat: "Neutrals & Grays" },
  { name: "Dark Cocoa", hex: "#2c1d11", cat: "Neutrals & Grays" }
];
